# Generated by Django 2.1.1 on 2019-06-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复发起者')),
            ],
            options={
                'verbose_name': '客户工作回复',
                'verbose_name_plural': '客户工作回复',
                'db_table': 'works_reply',
            },
        ),
        migrations.CreateModel(
            name='SubReplyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='works.SubReplyWork', verbose_name='上级回复')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='works.ReplyWork', verbose_name='所属回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复发起者')),
            ],
            options={
                'verbose_name': '客户工作子回复',
                'verbose_name_plural': '客户工作子回复',
                'db_table': 'works_sub_reply',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/%Y/%m/files/', verbose_name='选择附件')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='附件原始名称')),
                ('delete', models.BooleanField(default=False, verbose_name='标记删除')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='customers.Customer', verbose_name='所属客户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '客户工作',
                'verbose_name_plural': '客户工作',
                'db_table': 'works_work',
            },
        ),
        migrations.AddField(
            model_name='replywork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='works.Work', verbose_name='回复的工作'),
        ),
    ]
