# Generated by Django 2.1.1 on 2019-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='单位名称')),
                ('nature', models.CharField(max_length=50, verbose_name='单位性质')),
                ('industry', models.CharField(max_length=200, verbose_name='所属行业')),
                ('area', models.CharField(max_length=200, verbose_name='所属地区')),
                ('type', models.CharField(max_length=50, verbose_name='客户类型')),
                ('business', models.CharField(max_length=50, verbose_name='业务类型')),
                ('linkman', models.CharField(max_length=50, verbose_name='联系人')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('variety', models.CharField(max_length=256, verbose_name='品种')),
                ('account', models.TextField(verbose_name='开户/交易情况')),
                ('situation', models.TextField(verbose_name='概况描述')),
                ('capital', models.CharField(blank=True, max_length=50, null=True, verbose_name='资金规模')),
                ('question', models.TextField(blank=True, null=True, verbose_name='企业问题')),
                ('needs', models.TextField(blank=True, null=True, verbose_name='需求情况')),
                ('difficulty', models.TextField(blank=True, null=True, verbose_name='开发难点')),
                ('support', models.TextField(blank=True, null=True, verbose_name='支持需要')),
                ('card', models.ImageField(blank=True, null=True, upload_to='static/%Y/%m/images/', verbose_name='选择名片')),
                ('card_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名片原始名称')),
                ('delete', models.BooleanField(default=False, verbose_name='标记删除')),
                ('text_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='备用1')),
                ('text_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='备用2')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers_customer',
            },
        ),
    ]
